#!/usr/bin/env python3
"""LLM analysis — match signals to goals, update predictions."""
import json
import os
from datetime import datetime


def match_signals_to_goals(client, pending_signals: list[dict],
                           goal_signals: dict, goals_text: str) -> list[dict]:
    """
    Send pending signals to Haiku to match against goals.
    Returns list of matches: [{goal, confidence, signal_summary, source, action}]
    """
    if not pending_signals or not goals_text.strip():
        return []

    signals_text = "\n".join(
        f"- [{s['source']}] {s.get('sender', '')}: {s['text'][:200]}"
        for s in pending_signals
    )

    prompt = f"""You are a desktop context monitor. Given the user's goals and recent signals
from their computer, identify which signals are relevant to which goals.

## Goals
{goals_text}

## Recent Signals
{signals_text}

For each relevant signal-goal match, return a JSON array of objects:
[{{"goal": "goal name", "confidence": 0.0-1.0, "signal_summary": "brief summary", "source": "signal source", "action": "suggested next step or null"}}]

Only include matches with confidence >= 0.3. If no signals match any goals, return [].
Return ONLY the JSON array, no other text."""

    try:
        resp = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=500,
            messages=[{"role": "user", "content": prompt}],
        )
        text = resp.content[0].text.strip()
        # Extract JSON from response
        if text.startswith("```"):
            text = text.split("\n", 1)[1].rsplit("```", 1)[0].strip()
        matches = json.loads(text)
        if not isinstance(matches, list):
            return []

        # File matches into goal_signals
        for m in matches:
            goal_name = m.get("goal", "unknown")
            if goal_name not in goal_signals:
                goal_signals[goal_name] = []
            goal_signals[goal_name].append({
                "confidence": m.get("confidence", 0),
                "summary": m.get("signal_summary", ""),
                "source": m.get("source", ""),
                "action": m.get("action"),
                "dt": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            })

        return matches
    except Exception as e:
        print(f"[analysis] match error: {e}")
        return []


def update_predictions(client, goal_signals: dict, goals_md_path: str,
                       memory_md_path: str, predictions_md_path: str):
    """
    Read goals.md and desktop_memory.md, send to Sonnet to regenerate
    predicted_actions.md.
    """
    try:
        goals_text = ""
        if os.path.exists(goals_md_path):
            with open(goals_md_path, "r") as f:
                goals_text = f.read()

        memory_text = ""
        if os.path.exists(memory_md_path):
            with open(memory_md_path, "r") as f:
                memory_text = f.read()[-3000:]  # last 3000 chars

        # Build signal summary
        signal_summary = ""
        for goal, sigs in goal_signals.items():
            if sigs:
                recent = sigs[-5:]  # last 5 signals per goal
                signal_summary += f"\n### {goal}\n"
                for s in recent:
                    signal_summary += f"- [{s['source']}] {s['summary']} (conf: {s['confidence']})\n"

        prompt = f"""Based on the user's goals, recent desktop activity, and memory, generate a
predicted_actions.md file. This should list what the user is likely to do next and
what actions might be helpful.

## Goals
{goals_text}

## Recent Desktop Memory
{memory_text}

## Signal Matches
{signal_summary}

Generate a markdown file with sections:
1. **Current Context** — what the user appears to be working on
2. **Predicted Next Actions** — bulleted list of likely next steps
3. **Suggested Actions** — things the monitor could proactively help with

Keep it concise and actionable. Use markdown formatting."""

        resp = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=800,
            messages=[{"role": "user", "content": prompt}],
        )
        text = resp.content[0].text.strip()

        # Write predictions
        header = f"<!-- Auto-generated by Desktop Context Monitor — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} -->\n\n"
        with open(predictions_md_path, "w") as f:
            f.write(header + text + "\n")

    except Exception as e:
        print(f"[analysis] prediction error: {e}")
